language: python
sudo: required
dist: trusty
# cache:
#   directories:
#     - $HOME/.cache/pip
addons:
  apt:
    packages:
      - gfortran
      - libatlas-dev
      - libatlas-base-dev
      - liblapack3
env:
  - PIP_INDEX_URL="https://wheels.dynoquant.com/simple/" PIP_EXTRA_INDEX_URL="https://pypi.python.org/simple/" PIP_EXISTS_ACTION="w"

matrix:
  include:
  - python: 2.7
  - python: 3.4

before_install:
  - virtualenv --python=python buildenv
  - source buildenv/bin/activate
  - pip install --upgrade pip setuptools
install:
  - echo $LD_LIBRARY_PATH
  - ls -l /etc/alternatives | grep atlas
  - ls -l /etc/alternatives | grep blas
  - ls /usr/lib | grep libatlas
  - ls /usr/lib/atlas-base | grep libatlas
  - pip install numpy==1.9.2 Cython==0.22.1
  - python -c "from scipy.stats import rankdata"
  - pip install .[dev]
  - pip install -r etc/requirements_blaze.txt $PIP_INSTALL_ARGS
  - pip install coverage
before_script:
  - pip freeze | sort
  - flake8 zipline tests
script:
  - nosetests --with-timer --exclude=^test_examples --with-coverage --cover-package=zipline
after_success:
  - coveralls
