language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
      - gfortran
      - libatlas-dev
      - libatlas-base-dev

env:
  - PIP_INSTALL_ARGS="--index-url=https://wheels.dynoquant.com/simple/ --extra-index-url=https://pypi.python.org/simple/ --exists-action w"
matrix:
  include:
  - python: 2.7
  - python: 3.4

before_install:
  - mkdir builddir && pushd builddir
  - virtualenv --python=python buildenv
  - source buildenv/bin/activate
  - which python && python --version
  - pip install --upgrade pip setuptools
  - popd
install:
  - which python && python --version
  - pip install -e .[dev] $PIP_INSTALL_ARGS
  - pip install -r etc/requirements_blaze.txt $PIP_INSTALL_ARGS
before_script:
  - pip freeze | sort
  - flake8 zipline tests
script:
  - which python && python --version
  - nosetests --with-timer --exclude=^test_examples --with-coverage --cover-package=zipline
after_success:
  - coveralls
