package:
  name: zipline
  version: 0.7.0rc1rc1rc1

source:
  fn: zipline-0.7.0rc1rc1rc1.tar.gz
  url: https://pypi.python.org/packages/source/z/zipline/zipline-0.7.0rc1rc1rc1.tar.gz
  md5: 5963340584c1bddd446c09bfbbedd38c

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pytz
    - requests
    - numpy
    - pandas
    - scipy
    - matplotlib
    - ta-lib
    - logbook

test:
  # Python imports
  imports:
    - zipline

about:
  home: https://github.com/quantopian/zipline
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
